# Change these first
owner: sahli-interactive # Your GitHub organization or username, where this repository lives
repo: status.sahli-interactive.ch # The name of this repository

sites:
  - name: "Apart Hotel Adelboden"
    url: https://www.aparthotel-adelboden.ch
  - name: "Cardinal Coolbox Promotion"
    url: https://win.cardinal.ch
  - name: "Cerletti Immobilien"
    url: https://www.cerlettimmobilien.ch
  - name: "Christen Gartenbau AG"
    url: https://www.christen-gartenbau.ch
  - name: "Creativ Personal AG"
    url: https://www.creativpersonal.ch
  - name: "Etage Est GmbH"
    url: https://www.etage-est.ch
  - name: "FAIRMED Kamerun"
    url: https://fairmed.cm
  - name: "FAIRMED Nepal"
    url: https://www.fairmed.org.np
  - name: "FAIRMED Schweiz"
    url: https://www.fairmed.ch
  - name: "FAIRMED Sri Lanka"
    url: http://fairmedsrilanka.org
  - name: "Forum Sumiswald"
    url: https://www.forum-sumiswald.ch
  - name: "Glas-Werkstatt Kräuchi"
    url: https://www.kraeuchi.ch
  - name: "Goju Kan Bern AG"
    url: https://www.gojukan.ch
  - name: "Hirter Bedachungen AG"
    url: https://www.hirter.ch
  - name: "Huldi + Stucki AG"
    url: https://www.huldi-stucki.ch
  - name: "Insecor"
    url: https://www.insecor.ch
  - name: "M & T Schreinerei GmbH"
    url: https://www.mt-schreinerei.ch
  - name: "Malerei Zimmermann"
    url: https://www.zimal.ch
  - name: "Masina. Gfeller. Nyffenegger"
    url: https://mgnrecht.ch
  - name: "Notariat Haas"
    url: https://www.notariat-haas.ch
  - name: "Philosophie.ch"
    url: https://www.philosophie.ch
  - name: "Rüfenacht Elektro AG"
    url: https://www.ruefenacht-elektro.ch
  - name: "sahli:interactive"
    url: https://sahli-interactive.ch
  - name: "SahliBeschriftung"
    url: https://www.sahlibeschriftung.ch
  - name: "sahli.app"
    url: https://sahli.app
  - name: "Sport Amstutz"
    url: https://www.sport-amstutz.ch
  - name: "Traumbaum"
    url: https://traumbaum.ch
  - name: "urSIGN"
    url: https://www.ursign.ch
    
assignees:
  - m43nu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sahli-interactive.ch
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - sahli:interactive
  introTitle: "Status aller Webseite die von der sahli:interactive betrieben werden."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
