# Change these first
owner: sahli-interactive # Your GitHub organization or username, where this repository lives
repo: status.sahli-interactive.ch # The name of this repository

sites:
  - name: "Aare Bier Strom-Dashboard"
    url: https://aarebier.gerberenergietechnik.ch
    assignees:
      - m43nu
  - name: "ARAMIS SAR Service"
    url: https://datenausgabe.aramis.admin.ch
    assignees:
      - m43nu
  - name: "Autoverkehr Group"
    url: https://www.autoverkehr.ch
    assignees:
      - peperoli
  - name: "Disegnato"
    url: https://www.disegnato.ch
    assignees:
      - peperoli
  - name: "Cardinal Coolbox Promotion"
    url: https://win.cardinal.ch
    assignees:
      - m43nu
  - name: "Cerletti Immobilien"
    url: https://www.cerlettimmobilien.ch
    assignees:
      - m43nu
  - name: "Christen Gartenbau AG"
    url: https://www.christen-gartenbau.ch
    assignees:
      - m43nu
  - name: "Creativ Personal AG"
    url: https://www.creativpersonal.ch
    assignees:
      - m43nu
  - name: "Etage Est GmbH"
    url: https://www.etage-est.ch
    assignees:
      - m43nu
  - name: "F.G. Pfister"
    url: https://www.fgpfister.ch
    assignees:
      - peperoli
  - name: "FAIRMED Schweiz"
    url: https://www.fairmed.ch
    assignees:
      - peperoli
  - name: "FAIRMED Kamerun"
    url: https://fairmed.cm
    assignees:
      - m43nu
  - name: "FAIRMED Nepal"
    url: https://www.fairmed.org.np
    assignees:
      - m43nu
  - name: "FAIRMED Sri Lanka"
    url: https://fairmedsrilanka.org
    assignees:
      - m43nu
  - name: "Farbwerk Herren"
    url: https://www.farbwerkag.ch
    assignees:
      - peperoli
  - name: "Farbwerk Herren Online-Shop"
    url: https://shop.farbwerkag.ch
    assignees:
      - m43nu
  - name: "FTEM Karate"
    url: https://www.ftem-karate.ch
    assignees:
      - m43nu
  - name: "Germann Treuhand"
    url: https://www.germann-treuhand.ch
    assignees:
      - peperoli
  - name: "Glas-Werkstatt Kräuchi"
    url: https://www.kraeuchi.ch
    assignees:
      - m43nu
  - name: "Goju Kan Bern AG"
    url: https://www.gojukan.ch
    assignees:
      - m43nu
  - name: "Haus des Sports"
    url: https://www.hausdessports.ch
    assignees:
      - m43nu
  - name: "Heidadorf Visperterminen"
    url: https://www.heidadorf.ch
    assignees:
      - m43nu
  - name: "Hilscher Swiss"
    url: https://www.hilscher.ch
    assignees:
      - m43nu
  - name: "Hofmatt Uettligen"
    url: https://www.hofmattuettligen.ch
    assignees:
      - peperoli
  - name: "Huldi + Stucki AG"
    url: https://www.huldi-stucki.ch
    assignees:
      - m43nu
  - name: "Initiative Schweiz"
    url: https://www.initiative-schweiz.org
    assignees:
      - peperoli
  - name: "Insecor"
    url: https://www.insecor.ch
    assignees:
      - m43nu
  - name: "Koor Baumanagement"
    url: https://www.koor-baumanagement.ch
    assignees:
      - peperoli
  - name: "M & T Schreinerei GmbH"
    url: https://www.mt-schreinerei.ch
    assignees:
      - m43nu
  - name: "Malerei Zimmermann"
    url: https://www.zimal.ch
    assignees:
      - peperoli
  - name: "Masina. Gfeller. Nyffenegger"
    url: https://mgnrecht.ch
    assignees:
      - m43nu
  - name: "MLS Architekten"
    url: https://www.mls-architekten.ch
    assignees:
      - m43nu
  - name: "Notariat Haas"
    url: https://www.notariat-haas.ch
    assignees:
      - peperoli
  - name: "Nuwa"
    url: https://www.nuwa.swiss
    assignees:
      - peperoli
  - name: "Philosophie.ch"
    url: https://www.philosophie.ch
    assignees:
      - m43nu
  - name: "René Otter Architekten GmbH"
    url: https://reneotter.ch
    assignees:
      - m43nu
  - name: "Rudolf Obrecht AG"
    url: https://www.rudolfobrecht.com
    assignees:
      - peperoli
  - name: "Rüfenacht Elektro AG"
    url: https://www.ruefenacht-elektro.ch
    assignees:
      - peperoli
  - name: "sahli:interactive"
    url: https://sahli-interactive.ch
    assignees:
      - peperoli
  - name: "SahliBeschriftung"
    url: https://www.sahlibeschriftung.ch
    assignees:
      - peperoli
  - name: "sahli.app"
    url: https://sahli.app
    assignees:
      - m43nu
      - peperoli
  - name: "Salzmann Uhren & Bijouterie"
    url: https://www.zeitfuersalzmann.ch
    assignees:
      - peperoli
  - name: "Schnyder Werbung"
    url: https://schnyder-werbung.ch
    assignees:
      - m43nu
  - name: "Siloah Energie-Dashboard"
    url: https://zevsiloahsued.gerberenergietechnik.ch
    assignees:
      - m43nu
  - name: "Sorglos Design"
    url: https://www.sorglos-design.ch/
    assignees:
      - peperoli
  - name: "Sport Amstutz"
    url: https://www.sport-amstutz.ch
    assignees:
      - m43nu
  - name: "TECTON"
    url: https://www.tecton.ch
    assignees:
      - m43nu
  - name: "tubus GmbH"
    url: https://tubusgmbh.ch
    assignees:
      - peperoli
  - name: "Traumbaum"
    url: https://traumbaum.ch
    assignees:
      - m43nu
  - name: "urSIGN"
    url: https://www.ursign.ch
    assignees:
      - m43nu
  - name: "Ziegelhüsi"
    url: https://www.ziegelhuesi.ch
    assignees:
      - peperoli
  - name: "Zwahlen & Wieser Energie-Dashboard"
    url: https://zwahlen-wieser.gerberenergietechnik.ch
    assignees:
      - m43nu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sahli-interactive.ch
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - sahli:interactive
  introTitle: "Status aller Webseite die von der sahli:interactive betrieben werden."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
